# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3b8fdd7f3a3b1e8f6dce582a483c27339fefc2c33c58650a623e70849d451c3cced55129b729a6a086f9706a8794fbe240226419632786f284bb71f1f1baecb7

test:
  secret_key_base: af1255fa061ce79c77e17172a87bc5da7f1cae14279a766494c1df2bbd52ac56b27241552b2c1672893018b54c329745e419fb0af34b33a40a9b2ab971b4cf54

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
